direction: down

classes: {
  composition: {
    style.stroke: "#333333"
  }
  dependency: {
    style.stroke-dash: 3
  }
  inheritance: {
    target-arrowhead.shape: triangle
    style.stroke: "#333333"
  }
  implementation: {
    style.stroke-dash: 3
    target-arrowhead.shape: triangle
  }
}

AgentEnvironment: "AgentEnvironment <<type alias>>" {
  shape: class
}

TmuxEnvironment: "TmuxEnvironment <<frozen dataclass>>" {
  shape: class
  session: str
}

# Relationships
TmuxEnvironment -> AgentEnvironment: { class: implementation }
