direction: down

classes: {
  composition: {
    style.stroke: "#333333"
  }
  dependency: {
    style.stroke-dash: 3
  }
  inheritance: {
    target-arrowhead.shape: triangle
    style.stroke: "#333333"
  }
  implementation: {
    style.stroke-dash: 3
    target-arrowhead.shape: triangle
  }
}

SpecRepresentation: "SpecRepresentation <<protocol>>" {
  shape: class
  +name(): str
  +file_extensions(): "tuple[str, ...]"
  +describe_for_spec_writer(): str
  +describe_for_consumer(): str
}

PythonStubSpec: "PythonStubSpec <<frozen dataclass>>" {
  shape: class
  include_type_hints: bool
  +name(): str
  +file_extensions(): "tuple[str, ...]"
  +describe_for_spec_writer(): str
  +describe_for_consumer(): str
}

# Relationships
PythonStubSpec -> SpecRepresentation: satisfies { class: implementation }
